// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	pgconn "github.com/jackc/pgx/v5/pgconn"

	pgx "github.com/jackc/pgx/v5"

	transferdb "github.com/danipurwadi/internal-transfer-system/business/transferbus/stores/transferdb"

	transferdbgen "github.com/danipurwadi/internal-transfer-system/business/transferbus/stores/transferdb/gen"
)

// TxQuerier is an autogenerated mock type for the TxQuerier type
type TxQuerier struct {
	mock.Mock
}

type TxQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *TxQuerier) EXPECT() *TxQuerier_Expecter {
	return &TxQuerier_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, arg
func (_m *TxQuerier) CreateAccount(ctx context.Context, arg transferdbgen.CreateAccountParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, transferdbgen.CreateAccountParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxQuerier_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type TxQuerier_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - arg transferdbgen.CreateAccountParams
func (_e *TxQuerier_Expecter) CreateAccount(ctx interface{}, arg interface{}) *TxQuerier_CreateAccount_Call {
	return &TxQuerier_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, arg)}
}

func (_c *TxQuerier_CreateAccount_Call) Run(run func(ctx context.Context, arg transferdbgen.CreateAccountParams)) *TxQuerier_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transferdbgen.CreateAccountParams))
	})
	return _c
}

func (_c *TxQuerier_CreateAccount_Call) Return(_a0 error) *TxQuerier_CreateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxQuerier_CreateAccount_Call) RunAndReturn(run func(context.Context, transferdbgen.CreateAccountParams) error) *TxQuerier_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransaction provides a mock function with given fields: ctx, arg
func (_m *TxQuerier) CreateTransaction(ctx context.Context, arg transferdbgen.CreateTransactionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, transferdbgen.CreateTransactionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxQuerier_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type TxQuerier_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - arg transferdbgen.CreateTransactionParams
func (_e *TxQuerier_Expecter) CreateTransaction(ctx interface{}, arg interface{}) *TxQuerier_CreateTransaction_Call {
	return &TxQuerier_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, arg)}
}

func (_c *TxQuerier_CreateTransaction_Call) Run(run func(ctx context.Context, arg transferdbgen.CreateTransactionParams)) *TxQuerier_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transferdbgen.CreateTransactionParams))
	})
	return _c
}

func (_c *TxQuerier_CreateTransaction_Call) Return(_a0 error) *TxQuerier_CreateTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxQuerier_CreateTransaction_Call) RunAndReturn(run func(context.Context, transferdbgen.CreateTransactionParams) error) *TxQuerier_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// CreditAccount provides a mock function with given fields: ctx, arg
func (_m *TxQuerier) CreditAccount(ctx context.Context, arg transferdbgen.CreditAccountParams) (pgconn.CommandTag, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreditAccount")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, transferdbgen.CreditAccountParams) (pgconn.CommandTag, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transferdbgen.CreditAccountParams) pgconn.CommandTag); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, transferdbgen.CreditAccountParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxQuerier_CreditAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreditAccount'
type TxQuerier_CreditAccount_Call struct {
	*mock.Call
}

// CreditAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - arg transferdbgen.CreditAccountParams
func (_e *TxQuerier_Expecter) CreditAccount(ctx interface{}, arg interface{}) *TxQuerier_CreditAccount_Call {
	return &TxQuerier_CreditAccount_Call{Call: _e.mock.On("CreditAccount", ctx, arg)}
}

func (_c *TxQuerier_CreditAccount_Call) Run(run func(ctx context.Context, arg transferdbgen.CreditAccountParams)) *TxQuerier_CreditAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transferdbgen.CreditAccountParams))
	})
	return _c
}

func (_c *TxQuerier_CreditAccount_Call) Return(_a0 pgconn.CommandTag, _a1 error) *TxQuerier_CreditAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxQuerier_CreditAccount_Call) RunAndReturn(run func(context.Context, transferdbgen.CreditAccountParams) (pgconn.CommandTag, error)) *TxQuerier_CreditAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DebitAccount provides a mock function with given fields: ctx, arg
func (_m *TxQuerier) DebitAccount(ctx context.Context, arg transferdbgen.DebitAccountParams) (pgconn.CommandTag, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DebitAccount")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, transferdbgen.DebitAccountParams) (pgconn.CommandTag, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transferdbgen.DebitAccountParams) pgconn.CommandTag); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, transferdbgen.DebitAccountParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxQuerier_DebitAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebitAccount'
type TxQuerier_DebitAccount_Call struct {
	*mock.Call
}

// DebitAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - arg transferdbgen.DebitAccountParams
func (_e *TxQuerier_Expecter) DebitAccount(ctx interface{}, arg interface{}) *TxQuerier_DebitAccount_Call {
	return &TxQuerier_DebitAccount_Call{Call: _e.mock.On("DebitAccount", ctx, arg)}
}

func (_c *TxQuerier_DebitAccount_Call) Run(run func(ctx context.Context, arg transferdbgen.DebitAccountParams)) *TxQuerier_DebitAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transferdbgen.DebitAccountParams))
	})
	return _c
}

func (_c *TxQuerier_DebitAccount_Call) Return(_a0 pgconn.CommandTag, _a1 error) *TxQuerier_DebitAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxQuerier_DebitAccount_Call) RunAndReturn(run func(context.Context, transferdbgen.DebitAccountParams) (pgconn.CommandTag, error)) *TxQuerier_DebitAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, accountID
func (_m *TxQuerier) GetAccount(ctx context.Context, accountID int64) (transferdbgen.Account, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 transferdbgen.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (transferdbgen.Account, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) transferdbgen.Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(transferdbgen.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxQuerier_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type TxQuerier_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
func (_e *TxQuerier_Expecter) GetAccount(ctx interface{}, accountID interface{}) *TxQuerier_GetAccount_Call {
	return &TxQuerier_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, accountID)}
}

func (_c *TxQuerier_GetAccount_Call) Run(run func(ctx context.Context, accountID int64)) *TxQuerier_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TxQuerier_GetAccount_Call) Return(_a0 transferdbgen.Account, _a1 error) *TxQuerier_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxQuerier_GetAccount_Call) RunAndReturn(run func(context.Context, int64) (transferdbgen.Account, error)) *TxQuerier_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccounts provides a mock function with given fields: ctx, accountIds
func (_m *TxQuerier) GetAccounts(ctx context.Context, accountIds []int64) ([]transferdbgen.Account, error) {
	ret := _m.Called(ctx, accountIds)

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 []transferdbgen.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]transferdbgen.Account, error)); ok {
		return rf(ctx, accountIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []transferdbgen.Account); ok {
		r0 = rf(ctx, accountIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transferdbgen.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, accountIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxQuerier_GetAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccounts'
type TxQuerier_GetAccounts_Call struct {
	*mock.Call
}

// GetAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - accountIds []int64
func (_e *TxQuerier_Expecter) GetAccounts(ctx interface{}, accountIds interface{}) *TxQuerier_GetAccounts_Call {
	return &TxQuerier_GetAccounts_Call{Call: _e.mock.On("GetAccounts", ctx, accountIds)}
}

func (_c *TxQuerier_GetAccounts_Call) Run(run func(ctx context.Context, accountIds []int64)) *TxQuerier_GetAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *TxQuerier_GetAccounts_Call) Return(_a0 []transferdbgen.Account, _a1 error) *TxQuerier_GetAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxQuerier_GetAccounts_Call) RunAndReturn(run func(context.Context, []int64) ([]transferdbgen.Account, error)) *TxQuerier_GetAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, accountID
func (_m *TxQuerier) GetBalance(ctx context.Context, accountID int64) (decimal.Decimal, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (decimal.Decimal, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) decimal.Decimal); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxQuerier_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type TxQuerier_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
func (_e *TxQuerier_Expecter) GetBalance(ctx interface{}, accountID interface{}) *TxQuerier_GetBalance_Call {
	return &TxQuerier_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, accountID)}
}

func (_c *TxQuerier_GetBalance_Call) Run(run func(ctx context.Context, accountID int64)) *TxQuerier_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TxQuerier_GetBalance_Call) Return(_a0 decimal.Decimal, _a1 error) *TxQuerier_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxQuerier_GetBalance_Call) RunAndReturn(run func(context.Context, int64) (decimal.Decimal, error)) *TxQuerier_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetTx provides a mock function with given fields: ctx
func (_m *TxQuerier) GetTx(ctx context.Context) (pgx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTx")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxQuerier_GetTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTx'
type TxQuerier_GetTx_Call struct {
	*mock.Call
}

// GetTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TxQuerier_Expecter) GetTx(ctx interface{}) *TxQuerier_GetTx_Call {
	return &TxQuerier_GetTx_Call{Call: _e.mock.On("GetTx", ctx)}
}

func (_c *TxQuerier_GetTx_Call) Run(run func(ctx context.Context)) *TxQuerier_GetTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TxQuerier_GetTx_Call) Return(_a0 pgx.Tx, _a1 error) *TxQuerier_GetTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxQuerier_GetTx_Call) RunAndReturn(run func(context.Context) (pgx.Tx, error)) *TxQuerier_GetTx_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: tx
func (_m *TxQuerier) WithTx(tx pgx.Tx) transferdb.TxQuerier {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 transferdb.TxQuerier
	if rf, ok := ret.Get(0).(func(pgx.Tx) transferdb.TxQuerier); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transferdb.TxQuerier)
		}
	}

	return r0
}

// TxQuerier_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type TxQuerier_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx pgx.Tx
func (_e *TxQuerier_Expecter) WithTx(tx interface{}) *TxQuerier_WithTx_Call {
	return &TxQuerier_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *TxQuerier_WithTx_Call) Run(run func(tx pgx.Tx)) *TxQuerier_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgx.Tx))
	})
	return _c
}

func (_c *TxQuerier_WithTx_Call) Return(_a0 transferdb.TxQuerier) *TxQuerier_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxQuerier_WithTx_Call) RunAndReturn(run func(pgx.Tx) transferdb.TxQuerier) *TxQuerier_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewTxQuerier creates a new instance of TxQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxQuerier {
	mock := &TxQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
