// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TraceIDFn is an autogenerated mock type for the TraceIDFn type
type TraceIDFn struct {
	mock.Mock
}

type TraceIDFn_Expecter struct {
	mock *mock.Mock
}

func (_m *TraceIDFn) EXPECT() *TraceIDFn_Expecter {
	return &TraceIDFn_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *TraceIDFn) Execute(ctx context.Context) string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TraceIDFn_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type TraceIDFn_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TraceIDFn_Expecter) Execute(ctx interface{}) *TraceIDFn_Execute_Call {
	return &TraceIDFn_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *TraceIDFn_Execute_Call) Run(run func(ctx context.Context)) *TraceIDFn_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TraceIDFn_Execute_Call) Return(_a0 string) *TraceIDFn_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TraceIDFn_Execute_Call) RunAndReturn(run func(context.Context) string) *TraceIDFn_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewTraceIDFn creates a new instance of TraceIDFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTraceIDFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *TraceIDFn {
	mock := &TraceIDFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
