// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

type Logger_Expecter struct {
	mock *mock.Mock
}

func (_m *Logger) EXPECT() *Logger_Expecter {
	return &Logger_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, msg, v
func (_m *Logger) Execute(ctx context.Context, msg string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, msg)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Logger_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Logger_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - v ...interface{}
func (_e *Logger_Expecter) Execute(ctx interface{}, msg interface{}, v ...interface{}) *Logger_Execute_Call {
	return &Logger_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{ctx, msg}, v...)...)}
}

func (_c *Logger_Execute_Call) Run(run func(ctx context.Context, msg string, v ...interface{})) *Logger_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *Logger_Execute_Call) Return() *Logger_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Execute_Call) RunAndReturn(run func(context.Context, string, ...interface{})) *Logger_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
